build/yakworks/builder/jdk11.build: build/yakworks/builder/core.build
build/yakworks/builder/jdk8.build: build/yakworks/builder/core.build
build/yakworks/builder/core.build: build/yakworks/builder/base.build
build/yakworks/builder/jre11.build: build/yakworks/builder/core.build
build/yakworks/builder/repo-job.build: build/yakworks/builder/core.build
build/yakworks/bullseye/jdk11.build: build/yakworks/bullseye/core.build
build/yakworks/bullseye/docker-jdk11.build: build/yakworks/bullseye/jdk11.build
build/yakworks/bullseye/docker.build: build/yakworks/bullseye/core.build
build/yakworks/bullseye/core.build: build/yakworks/bullseye/base.build
build/yakworks/bullseye/dev.build: build/yakworks/bullseye/jdk11.build
build/yakworks/bullseye/helm.build: build/yakworks/bullseye/core.build
