build/docker.io/yakworks/builder/jdk11.build: build/docker.io/yakworks/builder/core.build
build/docker.io/yakworks/builder/jdk8.build: build/docker.io/yakworks/builder/core.build
build/docker.io/yakworks/builder/core.build: build/docker.io/yakworks/builder/base.build
build/docker.io/yakworks/builder/jre11.build: build/docker.io/yakworks/builder/core.build
build/docker.io/yakworks/builder/repo-job.build: build/docker.io/yakworks/builder/core.build
build/docker.io/yakworks/bullseye/jdk11.build: build/docker.io/yakworks/bullseye/core.build
build/docker.io/yakworks/bullseye/docker-jdk11.build: build/docker.io/yakworks/bullseye/jdk11.build
build/docker.io/yakworks/bullseye/jdk17.build: build/docker.io/yakworks/bullseye/core.build
build/docker.io/yakworks/bullseye/docker.build: build/docker.io/yakworks/bullseye/core.build
build/docker.io/yakworks/bullseye/core.build: build/docker.io/yakworks/bullseye/base.build
build/docker.io/yakworks/bullseye/jre11.build: build/docker.io/yakworks/bullseye/base.build
build/docker.io/yakworks/bullseye/jre17.build: build/docker.io/yakworks/bullseye/base.build
build/docker.io/yakworks/bullseye/core-psql14.build: build/docker.io/yakworks/bullseye/core.build
build/docker.io/yakworks/bullseye/dev.build: build/docker.io/yakworks/bullseye/jdk11.build
build/docker.io/yakworks/bullseye/aws.build: build/docker.io/yakworks/bullseye/core.build
build/docker.io/yakworks/bullseye/helm.build: build/docker.io/yakworks/bullseye/core.build
build/docker.io/yakworks/bookworm/jdk21.build: build/docker.io/yakworks/bookworm/core.build
build/docker.io/yakworks/bookworm/docker-jdk21.build: build/docker.io/yakworks/bookworm/jdk21.build
build/docker.io/yakworks/bookworm/core.build: build/docker.io/yakworks/bookworm/base.build
build/docker.io/yakworks/bookworm/mkdocs-server.build: build/docker.io/yakworks/bookworm/nginx-python.build
build/docker.io/yakworks/bookworm/jre21.build: build/docker.io/yakworks/bookworm/base.build
build/docker.io/yakworks/bookworm/mkdocs.build: build/docker.io/yakworks/bookworm/nginx-python.build
