ARG REGISTRY
FROM $REGISTRY/builder:node

# parallel
RUN apk add --no-cache parallel && \
    rm -rf /var/cache/apk/*

# java
RUN wget --quiet https://cdn.azul.com/public_keys/alpine-signing@azul.com-5d5dc44c.rsa.pub -P /etc/apk/keys/ && \
    echo "https://repos.azul.com/zulu/alpine" >> /etc/apk/repositories && \
    apk --no-cache add zulu11-jdk

ENV JAVA_HOME=/usr/lib/jvm/zulu11-ca

# adds in some things needed for java ui and reporting, like fonts
RUN apk add --no-cache dumb-init xvfb fontconfig ttf-dejavu && \
    rm -rf /var/cache/apk/*
